version: '3'
services:
  engine_telemetry:
    image: "graphiteapp/graphite-statsd"
    environment:
      STATSD_HOST: host.docker.internal
    ports:
      # This is only to expose it to the external network
      - "3002:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"